
GET http://localhost:3000/authors
###
POST http://localhost:3000/authors
Content-Type: application/json

{
    "blogAuthor": "Johannes",
    "blogpost": ["6412cad47cb4a5f5c216d311", "6412ebeb850db976f2669089"]
}